---

GENERAL:
  csv_file_name: example/data/flowershop.csv
  db_table_name: flowershop
  db_file_path: domains/flowershop-dbase.db
  ontology_file_path: domains/flowershop-rules.json


ONTOLOGY:
  informable_slots: [type, price, occasion]

  requestable_slots: [price, color]

  system_requestable_slots: [price, occasion]
