---

package: plato.utilities.parser.parse_dstc2
class: Parser
arguments:
  data_path: <path to where the DSTC2 data was unzipped>
  ontology: plato/example/domains/CamRestaurants-rules.json
  database: plato/example/domains/CamRestaurants-dbase.db
