---

GENERAL:
  interaction_mode: simulation
  agents: 1
  generic: False
  runs: 1

  experience_logs:
    save: True
    load: False
    path: logs/CamRest_model_DST

  global_arguments:
    ontology: example/domains/CamRestaurants-rules.json
    database: example/domains/CamRestaurants-dbase.db
    db_type: sql
    domain: CamRest

DIALOGUE:
  num_dialogues: 10
  initiative: system
  domain: CamRest

AGENT_0:
  role: system

  NLU:
    package: plato.agent.component.nlu.slot_filling_nlu
    class: SlotFillingNLU

  DM:
    package: plato.agent.component.dialogue_manager.dialogue_manager_generic
    class: DialogueManagerGeneric
    arguments:
      DST:
        package: applications.cambridge_restaurants.camrest_dst
        class: CamRestDST
        arguments:
          model_path: models/camrest_dst/sys/experiment_run/model

      policy:
        package: plato.agent.component.dialogue_policy.slot_filling_policy
        class: HandcraftedPolicy

  NLG:
    package: plato.agent.component.nlg.slot_filling_nlg
    class: SlotFillingNLG

  USER_SIMULATOR:
    package: plato.agent.component.user_simulator.agenda_based_user_simulator.agenda_based_us
    class: AgendaBasedUS
    arguments:
      goals_path: data/goals.pkl
      simulator: agenda
      patience: 5
      pop_distribution: [1.0]
      slot_confuse_prob: 0.0
      op_confuse_prob: 0.0
      value_confuse_prob: 0.0
      nlu: slot_filling
      nlg: slot_filling
